### ISSUE TITLE
NoClassDefFoundError: Hashing

### ISSUE THREAD

**Issue by skwerlman** [Trystan-Cannon/Java-Krist-Miner#5]
When closing the miner, it crashes with:

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at krist.miner.Utils.subSHA256(Utils.java:137)
        at krist.miner.ClusterMiner.run(ClusterMiner.java:67)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.hash.Hashing
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```

**Comment by skwerlman** [comment]
Nvm, it doesn't throw it when closing; rather, it throws it when I hit 'Begin Mining'

**Comment by skwerlman** [comment]
Nvm yet again; I had downloaded guava to the wrong place. Sorry for the noise.

**Comment by oldmud0** [comment]
People still use this? I would consider this a sample implementation than a real one.

**Comment by skwerlman** [comment]
Are there any more up-to-date implementations? I haven't been able fond any, tho I haven't looked too hard.

**Comment by oldmud0** [comment]
err, I don't remember where the full list is, but just look through the CC thread and you should find a couple of better ones that use CUDA or "enhanced" algorithms
